name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Lint
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: workspaces run lint

      - name: Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: workspaces run compile

      - name: Test
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: workspaces run test --coverage
