name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: workspaces run lint

      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: workspaces run compile

      - name: Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: workspaces run test --coverage
